# name: Deploy Node.js Application To AWS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18"

#       - name: Install dependencies
#         run: npm install

#       - name: Deploy to EC2 via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.AWS_HOST }}
#           username: ${{ secrets.AWS_USER }}
#           key: ${{ secrets.AWS_SSH_KEY }}
#           script: |
#             cd /home/ubuntu/ciditestrepo
#             git pull origin main
#             docker compose down
#             docker compose build -t
#             docker composer up -d

name: Deploy Node.js Application To AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/ciditestrepo
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
